config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("ideas.urls")),
    path("tools/", include("tools.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ideas/urls.py
from django.urls import path
from . import views

app_name = "ideas"

urlpatterns = [
    path("", views.idea_list, name="idea_list"),
    path("<int:pk>/", views.idea_detail, name="idea_detail"),
    path("create/", views.idea_create, name="idea_create"),
    path("<int:pk>/update", views.idea_update, name="idea_update"),
    path("<int:pk>/delete", views.idea_delete, name="idea_delete"),
]

tools/urls.py
from django.urls import path
from . import views

app_name = "tools"

urlpatterns = [
    path("", views.tool_list, name="tool_list"),
    path("<int:pk>/", views.tool_detail, name="tool_detail"),
    path("create/", views.tool_create, name="tool_create"),
    path("<int:pk>/update", views.tool_update, name="tool_update"),
    path("<int:pk>/delete", views.tool_delete, name="tool_delete"),
]

core/models.py
from django.db import models

# Create your models here.

ideas/models.py
from django.db import models
from django.shortcuts import reverse
from config.utils import uuid_name_upload_to


class Idea(models.Model):

    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to=uuid_name_upload_to)
    content = models.TextField()
    interest = models.PositiveIntegerField(default=0)
    devtool = models.ForeignKey(
        "tools.Tool", on_delete=models.CASCADE, related_name="ideas"
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("ideas:idea_detail", kwargs={"pk": self.pk})

tools/models.py
from django.db import models
from django.shortcuts import reverse


class Tool(models.Model):
    name = models.CharField(max_length=50)
    kind = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("tools:tool_detail", kwargs={"pk": self.pk})

core/views.py
from django.shortcuts import render

# Create your views here.

ideas/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

import json

from . import models


def idea_list(request):
    if request.method == "POST":
        pk = request.POST.get("pk", None)
        plus = int(request.POST.get("plus"))
        idea = get_object_or_404(models.Idea, pk=pk)
        if not (plus == -1 and idea.interest <= 0):
            models.Idea.objects.filter(pk=pk).update(interest=idea.interest + plus)
        ctx = {
            "idea_interest": get_object_or_404(models.Idea, pk=pk).interest,
        }
        return HttpResponse(json.dumps(ctx), content_type="application/json")
    else:
        posts = models.Idea.objects.all()
        ctx = {
            "posts": posts,
        }
        return render(request, "ideas/idea_list.html", ctx)


# class IdeaListView(ListView):
#     model = models.Idea


# idea_list = IdeaListView.as_view()


# def idea_detail(request, pk):
#     ctx = {
#         "pk": pk,
#     }
#     return render(request, "ideas/idea_detail.html", ctx)


class IdeaDetailView(DetailView):
    model = models.Idea


idea_detail = IdeaDetailView.as_view()


# def idea_create(request, pk):
#     pass


class IdeaCreateView(CreateView):
    model = models.Idea
    fields = "__all__"


idea_create = IdeaCreateView.as_view()


# def idea_update(request, pk):
#     pass


class IdeaUpdateView(UpdateView):
    model = models.Idea
    fields = "__all__"
    template_name_suffix = "_update_form"


idea_update = IdeaUpdateView.as_view()


# def idea_delete(request, pk):
#     pass


class IdeaDeleteView(DeleteView):
    model = models.Idea
    success_url = reverse_lazy("ideas:idea_list")


idea_delete = IdeaDeleteView.as_view()

tools/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from . import models

# def tool_list(request):
#     return render(request, "tools/tool_list.html")


class ToolListView(ListView):
    model = models.Tool


tool_list = ToolListView.as_view()


# def tool_detail(request, pk):
#     ctx = {
#         "pk": pk,
#     }
#     return render(request, "tools/tool_detail.html", ctx)


class ToolDetailView(DetailView):
    model = models.Tool


tool_detail = ToolDetailView.as_view()


# def tool_create(request, pk):
#     pass


class ToolCreateView(CreateView):
    model = models.Tool
    fields = "__all__"


tool_create = ToolCreateView.as_view()


# def tool_update(request, pk):
#     pass


class ToolUpdateView(UpdateView):
    model = models.Tool
    fields = "__all__"
    template_name_suffix = "_update_form"


tool_update = ToolUpdateView.as_view()


# def tool_delete(request, pk):
#     pass


class ToolDeleteView(DeleteView):
    model = models.Tool
    success_url = reverse_lazy("tools:tool_list")


tool_delete = ToolDeleteView.as_view()

core/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nagi's Ideabank</title>
</head>
<body>
    <nav>
        <span>My SW Idea Manage</span>
        <ul>
            <li><a href="{% url "ideas:idea_create" %}">아이디어 등록</a></li>
            <li><a href="{% url "ideas:idea_list" %}">아이디어 관리</a></li>
            <li><a href="{% url "tools:tool_create" %}">개발툴 등록</a></li>
            <li><a href="{% url "tools:tool_list" %}">개발툴 관리</a></li>
        </ul>
    </nav>
    {% block content %}
    {% endblock content %}
</body>
</html>

ideas/templates/ideas/idea_confirm_delete.html
{% extends 'ideas/layout.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{object}}?"</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}

ideas/templates/ideas/idea_detail.html
{% extends 'ideas/layout.html' %}

{% block content %}
    <h1>Idea Detail</h1>
    <div class="">  
        <img src="{{idea.image.url}}" alt="Idea image">
        <div class="">
            <h2>{{idea.title}}</h2>
            <ol style="list-style-type: decimical">
                <li>
                    <h4>아이디어 관심도 : </h4>
                    {{idea.interest}}
                </li>
                <li>
                    <h4>예상 개발 툴 : </h4>
                    {{idea.devtool.name}}   
                </li>
                <li>
                    <h4>아이디어 설명 : </h4>
                    {{idea.content}}
                </li>
            </ol>
            <a href="{% url "ideas:idea_delete" idea.pk %}">삭제</a>
            <a href="{% url "ideas:idea_list" %}">목록</a>
            <a href="{% url "ideas:idea_update" idea.pk %}">수정</a>


        </div>
    </div>
{% endblock content %}

ideas/templates/ideas/idea_form.html
{% extends 'ideas/layout.html' %}

{% block content %}
    <h1>Idea Register</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="SUBMIT">
    </form>
{% endblock content %}

ideas/templates/ideas/idea_list.html
{% extends 'ideas/layout.html' %}

{% block content %}
    <h1>Idea List</h1>
    <ul>
    {% for idea in posts %}
        <li>
            <img src="{{idea.image.url}}" alt="Idea image">
            <h3><a href="{{idea.get_absolute_url}}">{{idea.title}}</a></h3>
            <h4>예상 개발 툴 : {{idea.devtool.name}}</h4>
            <h4 class="idea-interest_{{idea.pk}}">아이디어 관심도 : {{idea.interest}}</h4>
            <div class="">
                <button class="interest-btn like" name={{idea.pk}}>🔺</button>
                <button class="interest-btn" name={{idea.pk}}>🔻</button>
            </div>
        </li>
    {% endfor %}
    </ul>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript">
        $(".interest-btn").click(function(){
            let plus = 0
            if ($(this).hasClass("like")){
                plus = 1
            }
            else{
                plus = -1
            }
            let pk = $(this).attr('name')
            $.ajax({
                type: "POST",
                url: "{% url "ideas:idea_list" %}",
                data: {"pk":pk, "csrfmiddlewaretoken": "{{ csrf_token }}", "plus": plus,},
                dataType: "json",
                success: function(response){
                    let change = $(".idea-interest_+"+pk)
                    $(".idea-interest_"+pk).html("아이디어 관심도 : "+response.idea_interest);

                }
            })
        })
    </script>
{% endblock content %}

ideas/templates/ideas/idea_update_form.html
{% extends 'ideas/layout.html' %}

{% block content %}
    <h1>Idea Detail Update</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="SUBMIT">
    </form>
{% endblock content %}

tools/templates/tools/layout.html
{% extends 'layout.html' %}

{% block content %}
{% endblock content %}

tools/templates/tools/tool_confirm_delete.html
{% extends 'tools/layout.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{object}}?"</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}

tools/templates/tools/tool_detail.html
{% extends 'tools/layout.html' %}

{% block content %}
    <h1>Tool Detail</h1>
    <div class="">  
        <div class="">
            <h2>{{tool.name}}</h2>
            <div class="">
                <h4>{{tool.kind}}</h4>
                <p>{{tool.description}}</p>
            </div>
            <hr>
            <div class="">
                <h3>만들 수 있는 SW 목록</h3>
                <ul>
                    {% for idea in tool.ideas.all %}
                        <li>{{idea}}</li>
                    {% endfor %}
                </ul>
            </div>

            
            <a href="{% url "tools:tool_delete" tool.pk %}">삭제</a>
            <a href="{% url "tools:tool_list" %}">목록</a>
            <a href="{% url "tools:tool_update" tool.pk %}">수정</a>


        </div>
    </div>
{% endblock content %}

tools/templates/tools/tool_form.html
{% extends 'tools/layout.html' %}

{% block content %}
    <h1>Tool Register</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="SUBMIT">
    </form>
{% endblock content %}

tools/templates/tools/tool_list.html
{% extends 'tools/layout.html' %}

{% block content %}
    <h1>Tool List</h1>
    <ul>
    {% for tool in object_list %}
        <li>
            <h4><a href="{{tool.get_absolute_url}}">{{tool.name}}</a></h4>
            <h4>{{tool.kind}}</h4>
            <p>{{tool.description}}</p>
        </li>
    {% endfor %}
    </ul>
{% endblock content %}

tools/templates/tools/tool_update_form.html
{% extends 'tools/layout.html' %}

{% block content %}
    <h1>Tool Detail Update</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="SUBMIT">
    </form>
{% endblock content %}